import{a as v,S as w,i as P}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function h(o,t){const n="https://pixabay.com",i="/api/",e="?key=44219732-b756856c5facc95b2951616e8",r=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`,s=n+i+e+r;return(await v.get(s)).data}const u=document.querySelector(".gallery"),q=new w(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"});function p(o){const t=o.hits.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:f,downloads:S})=>`<li class="gallery-item">
                <a class="gallery-link" href="${i}">
                <img class="gallery-img" src="${n}" alt="${e}">
                <div class="image-description">
                <p>Likes: ${r}</p>
                <p>Views: ${s}</p>
                <p>Comments ${f}</p>
                <p>Downloads ${S}</p>
                </div>
                </a>
                </li>`).join("");u.insertAdjacentHTML("beforeend",t),q.refresh()}const $=document.querySelector(".img-search-form"),y=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");let l,c,g;$.addEventListener("submit",M);m.addEventListener("click",O);async function M(o){if(o.preventDefault(),L(),u.innerHTML="",l=o.target.elements.query.value.trim(),c=1,l===""){a("Sorry, there are no search terms entered. Please try again!");return}b();try{const t=await h(l,c);if(g=Math.ceil(t.totalHits/15),t.totalHits===0){d(),a("Sorry, there are no images matching your search query. Please try again!");return}p(t)}catch(t){a(t)}d(),E(),o.target.reset()}async function O(){c+=1,b();try{const t=await h(l,c);p(t)}catch(t){a(t)}d(),E();const o=u.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:o*2})}function A(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}function a(o){P.error({message:o,messageColor:"white",backgroundColor:"red",position:"topRight"})}function E(){c>=g?(L(),a("We're sorry, but you've reached the end of search results.")):A()}
//# sourceMappingURL=commonHelpers.js.map
